# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/htc/m8/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/htc/m8

PRODUCT_COPY_FILES += \
    vendor/htc/m8/proprietary/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so \
    vendor/htc/m8/proprietary/vendor/lib/libril_spr-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril_spr-qc-qmi-1.so \
    vendor/htc/m8/proprietary/vendor/lib/libril_vzw-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril_vzw-qc-qmi-1.so
