# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/m8/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/m8/proprietary/blobs/gsm/bin/netmgrd:system/blobs/gsm/bin/netmgrd \
    vendor/htc/m8/proprietary/blobs/gsm/bin/qmuxd:system/blobs/gsm/bin/qmuxd \
    vendor/htc/m8/proprietary/blobs/gsm/lib/libmdmdetect.so:system/blobs/gsm/lib/libmdmdetect.so \
    vendor/htc/m8/proprietary/blobs/gsm/vendor/lib/libcneapiclient.so:system/blobs/gsm/vendor/lib/libcneapiclient.so \
    vendor/htc/m8/proprietary/blobs/gsm/vendor/lib/libconfigdb.so:system/blobs/gsm/vendor/lib/libconfigdb.so \
    vendor/htc/m8/proprietary/blobs/gsm/vendor/lib/libnetmgr.so:system/blobs/gsm/vendor/lib/libnetmgr.so \
    vendor/htc/m8/proprietary/blobs/gsm/vendor/lib/libperipheral_client.so:system/blobs/gsm/vendor/lib/libperipheral_client.so \
    vendor/htc/m8/proprietary/blobs/gsm/vendor/lib/libril-qc-qmi-1.so:system/blobs/gsm/vendor/lib/libril-qc-qmi-1.so \
    vendor/htc/m8/proprietary/blobs/gsm/vendor/lib/libril-qcril-hook-oem.so:system/blobs/gsm/vendor/lib/libril-qcril-hook-oem.so \
    vendor/htc/m8/proprietary/blobs/spr/bin/netmgrd:system/blobs/spr/bin/netmgrd \
    vendor/htc/m8/proprietary/blobs/spr/bin/qmuxd:system/blobs/spr/bin/qmuxd \
    vendor/htc/m8/proprietary/blobs/spr/lib/libmdmdetect.so:system/blobs/spr/lib/libmdmdetect.so \
    vendor/htc/m8/proprietary/blobs/spr/vendor/lib/libcneapiclient.so:system/blobs/spr/vendor/lib/libcneapiclient.so \
    vendor/htc/m8/proprietary/blobs/spr/vendor/lib/libconfigdb.so:system/blobs/spr/vendor/lib/libconfigdb.so \
    vendor/htc/m8/proprietary/blobs/spr/vendor/lib/libnetmgr.so:system/blobs/spr/vendor/lib/libnetmgr.so \
    vendor/htc/m8/proprietary/blobs/spr/vendor/lib/libperipheral_client.so:system/blobs/spr/vendor/lib/libperipheral_client.so \
    vendor/htc/m8/proprietary/blobs/spr/vendor/lib/libril-qc-qmi-1.so:system/blobs/spr/vendor/lib/libril-qc-qmi-1.so \
    vendor/htc/m8/proprietary/blobs/spr/vendor/lib/libril-qcril-hook-oem.so:system/blobs/spr/vendor/lib/libril-qcril-hook-oem.so \
    vendor/htc/m8/proprietary/blobs/vzw/bin/netmgrd:system/blobs/vzw/bin/netmgrd \
    vendor/htc/m8/proprietary/blobs/vzw/bin/qmuxd:system/blobs/vzw/bin/qmuxd \
    vendor/htc/m8/proprietary/blobs/vzw/lib/libmdmdetect.so:system/blobs/vzw/lib/libmdmdetect.so \
    vendor/htc/m8/proprietary/blobs/vzw/vendor/lib/libcneapiclient.so:system/blobs/vzw/vendor/lib/libcneapiclient.so \
    vendor/htc/m8/proprietary/blobs/vzw/vendor/lib/libconfigdb.so:system/blobs/vzw/vendor/lib/libconfigdb.so \
    vendor/htc/m8/proprietary/blobs/vzw/vendor/lib/libnetmgr.so:system/blobs/vzw/vendor/lib/libnetmgr.so \
    vendor/htc/m8/proprietary/blobs/vzw/vendor/lib/libperipheral_client.so:system/blobs/vzw/vendor/lib/libperipheral_client.so \
    vendor/htc/m8/proprietary/blobs/vzw/vendor/lib/libril-qc-qmi-1.so:system/blobs/vzw/vendor/lib/libril-qc-qmi-1.so \
    vendor/htc/m8/proprietary/blobs/vzw/vendor/lib/libril-qcril-hook-oem.so:system/blobs/vzw/vendor/lib/libril-qcril-hook-oem.so
