# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/htc/m8d/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/htc/m8d

PRODUCT_COPY_FILES += \
    vendor/htc/m8d/proprietary/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so
