# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/m8d/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/m8d/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/htc/m8d/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/htc/m8d/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/htc/m8d/proprietary/bin/radish:system/bin/radish \
    vendor/htc/m8d/proprietary/bin/rild:system/bin/rild \
    vendor/htc/m8d/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/htc/m8d/proprietary/etc/flp.conf:system/etc/flp.conf \
    vendor/htc/m8d/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/htc/m8d/proprietary/etc/izat.conf:system/etc/izat.conf \
    vendor/htc/m8d/proprietary/etc/sap.conf:system/etc/sap.conf \
    vendor/htc/m8d/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/htc/m8d/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/htc/m8d/proprietary/lib/libhtc_rilhook.so:system/lib/libhtc_rilhook.so \
    vendor/htc/m8d/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/htc/m8d/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/htc/m8d/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/htc/m8d/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/htc/m8d/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/htc/m8d/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/htc/m8d/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/htc/m8d/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/htc/m8d/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/htc/m8d/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/htc/m8d/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/htc/m8d/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/htc/m8d/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/htc/m8d/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/htc/m8d/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/htc/m8d/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/htc/m8d/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/htc/m8d/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/htc/m8d/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/htc/m8d/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/htc/m8d/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/htc/m8d/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/htc/m8d/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/htc/m8d/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so

PRODUCT_PACKAGES += \
    libril
