# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/flounder/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/gatekeeper.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.flounder.so \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/gralloc.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.tegra132.so \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/hwcomposer.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/hwcomposer.tegra132.so \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/keystore.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.flounder.so \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/memtrack.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/memtrack.tegra132.so \
    vendor/htc/flounder/proprietary/vendor/lib64/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfrsdk.so \
    vendor/htc/flounder/proprietary/vendor/lib64/libhtcacoustic.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhtcacoustic.so \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvapputil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvapputil.so \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvgr.so \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvos.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvos.so \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvrm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvrm.so \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvrm_graphics.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvrm_graphics.so
PRODUCT_COPY_FILES += \
    vendor/htc/flounder/proprietary/vendor/bin/glgps:$(TARGET_COPY_OUT_VENDOR)/bin/glgps \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/gps.bcm47521.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gps.bcm47521.so
