# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/s4-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/htc/s4-common/proprietary/etc/agps_rm:/system/etc/agps_rm \
        vendor/htc/s4-common/proprietary/bin/akmd:/system/bin/akmd \
        vendor/htc/s4-common/proprietary/bin/charging:/system/bin/charging \
        vendor/htc/s4-common/proprietary/bin/hci_qcomm_init:/system/bin/hci_qcomm_init \
        vendor/htc/s4-common/proprietary/bin/mm-qcamera-daemon:/system/bin/mm-qcamera-daemon \
        vendor/htc/s4-common/proprietary/bin/mpdecision:/system/bin/mpdecision \
        vendor/htc/s4-common/proprietary/bin/radish:/system/bin/radish \
        vendor/htc/s4-common/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
        vendor/htc/s4-common/proprietary/bin/thermald:/system/bin/thermald \
        vendor/htc/s4-common/proprietary/lib/libacdbloader.so:/system/lib/libacdbloader.so \
        vendor/htc/s4-common/proprietary/lib/libaudcal.so:/system/lib/libaudcal.so \
        vendor/htc/s4-common/proprietary/lib/hw/camera.vendor.msm8960.so:/system/lib/hw/camera.vendor.msm8960.so \
        vendor/htc/s4-common/proprietary/lib/libBeautyChat.so:/system/lib/libBeautyChat.so \
        vendor/htc/s4-common/proprietary/lib/libcameraasd.so:/system/lib/libcameraasd.so \
        vendor/htc/s4-common/proprietary/lib/libcameraface.so:/system/lib/libcameraface.so \
        vendor/htc/s4-common/proprietary/lib/libcamerapp.so:/system/lib/libcamerapp.so \
        vendor/htc/s4-common/proprietary/lib/libcam_oem_plugin.so:/system/lib/libcam_oem_plugin.so \
        vendor/htc/s4-common/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
        vendor/htc/s4-common/proprietary/lib/libHTC_DIS.so:/system/lib/libHTC_DIS.so \
        vendor/htc/s4-common/proprietary/lib/libhtccamera.so:/system/lib/libhtccamera.so \
        vendor/htc/s4-common/proprietary/lib/libimage-jpeg-dec-omx-comp.so:/system/lib/libimage-jpeg-dec-omx-comp.so \
        vendor/htc/s4-common/proprietary/lib/libimage-jpeg-enc-omx-comp.so:/system/lib/libimage-jpeg-enc-omx-comp.so \
        vendor/htc/s4-common/proprietary/lib/libimage-omx-common.so:/system/lib/libimage-omx-common.so \
        vendor/htc/s4-common/proprietary/lib/libmmcamera_faceproc.so:/system/lib/libmmcamera_faceproc.so \
        vendor/htc/s4-common/proprietary/lib/libmmcamera_frameproc.so:/system/lib/libmmcamera_frameproc.so \
        vendor/htc/s4-common/proprietary/lib/libmmcamera_hdr_lib.so:/system/lib/libmmcamera_hdr_lib.so \
        vendor/htc/s4-common/proprietary/lib/libmmcamera_image_stab.so:/system/lib/libmmcamera_image_stab.so \
        vendor/htc/s4-common/proprietary/lib/libmmcamera_interface2.so:/system/lib/libmmcamera_interface2.so \
        vendor/htc/s4-common/proprietary/lib/libmmcamera_rawchipproc.so:/system/lib/libmmcamera_rawchipproc.so \
        vendor/htc/s4-common/proprietary/lib/libmmcamera_statsproc31.so:/system/lib/libmmcamera_statsproc31.so \
        vendor/htc/s4-common/proprietary/lib/libmmcamera_wavelet_lib.so:/system/lib/libmmcamera_wavelet_lib.so \
        vendor/htc/s4-common/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
        vendor/htc/s4-common/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
        vendor/htc/s4-common/proprietary/lib/libmmmpod.so:/system/lib/libmmmpod.so \
        vendor/htc/s4-common/proprietary/lib/libmmstillomx.so:/system/lib/libmmstillomx.so \
        vendor/htc/s4-common/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
        vendor/htc/s4-common/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
        vendor/htc/s4-common/proprietary/lib/libgeofence.so:/system/lib/libgeofence.so \
        vendor/htc/s4-common/proprietary/lib/libloc_api_v02.so:/system/lib/libloc_api_v02.so \
        vendor/htc/s4-common/proprietary/vendor/lib/egl/eglsubAndroid.so:/system/vendor/lib/egl/eglsubAndroid.so \
        vendor/htc/s4-common/proprietary/vendor/lib/egl/libEGL_adreno.so:/system/vendor/lib/egl/libEGL_adreno.so \
        vendor/htc/s4-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:/system/vendor/lib/egl/libGLESv1_CM_adreno.so \
        vendor/htc/s4-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:/system/vendor/lib/egl/libGLESv2_adreno.so \
        vendor/htc/s4-common/proprietary/vendor/lib/egl/libGLESv2S3D_adreno.so:/system/vendor/lib/egl/libGLESv2S3D_adreno.so \
        vendor/htc/s4-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:/system/vendor/lib/egl/libq3dtools_adreno.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libadreno_utils.so:/system/vendor/lib/libadreno_utils.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libc2d2_a3xx.so:/system/vendor/lib/libc2d2_a3xx.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libc2d2_z180.so:/system/vendor/lib/libc2d2_z180.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libC2D2.so:/system/vendor/lib/libC2D2.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libCB.so:/system/vendor/lib/libCB.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libgsl.so:/system/vendor/lib/libgsl.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libllvm-a3xx.so:/system/vendor/lib/libllvm-a3xx.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libOpenCL.so:/system/vendor/lib/libOpenCL.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libOpenVG.so:/system/vendor/lib/libOpenVG.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libsc-a2xx.so:/system/vendor/lib/libsc-a2xx.so \
        vendor/htc/s4-common/proprietary/etc/firmware/a225p5_pm4.fw:/system/etc/firmware/a225p5_pm4.fw \
        vendor/htc/s4-common/proprietary/etc/firmware/a225_pfp.fw:/system/etc/firmware/a225_pfp.fw \
        vendor/htc/s4-common/proprietary/etc/firmware/a225_pm4.fw:/system/etc/firmware/a225_pm4.fw \
        vendor/htc/s4-common/proprietary/etc/firmware/vidc_1080p.fw:/system/etc/firmware/vidc_1080p.fw \
        vendor/htc/s4-common/proprietary/lib/libExtendedExtractor.so:/system/lib/libExtendedExtractor.so \
        vendor/htc/s4-common/proprietary/lib/libI420colorconvert.so:/system/lib/libI420colorconvert.so \
        vendor/htc/s4-common/proprietary/lib/libmm-color-convertor.so:/system/lib/libmm-color-convertor.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libqc-opt.so:/system/vendor/lib/libqc-opt.so \
        vendor/htc/s4-common/proprietary/lib/libdrmdecrypt.so:/system/lib/libdrmdecrypt.so \
        vendor/htc/s4-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:/system/vendor/lib/drm/libdrmwvmplugin.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libdrmfs.so:/system/vendor/lib/libdrmfs.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libdrmtime.so:/system/vendor/lib/libdrmtime.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libQSEEComAPI.so:/system/vendor/lib/libQSEEComAPI.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libwvdrm_L1.so:/system/vendor/lib/libwvdrm_L1.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libwvm.so:/system/vendor/lib/libwvm.so \
        vendor/htc/s4-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:/system/vendor/lib/libWVStreamControlAPI_L1.so \
        vendor/htc/s4-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:/system/vendor/lib/mediadrm/libwvdrmengine.so \
        vendor/htc/s4-common/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:/system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
        vendor/htc/s4-common/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:/system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
        vendor/htc/s4-common/proprietary/etc/firmware/wcnss.b00:/system/etc/firmware/wcnss.b00 \
        vendor/htc/s4-common/proprietary/etc/firmware/wcnss.b01:/system/etc/firmware/wcnss.b01 \
        vendor/htc/s4-common/proprietary/etc/firmware/wcnss.b02:/system/etc/firmware/wcnss.b02 \
        vendor/htc/s4-common/proprietary/etc/firmware/wcnss.b04:/system/etc/firmware/wcnss.b04 \
        vendor/htc/s4-common/proprietary/etc/firmware/wcnss.b05:/system/etc/firmware/wcnss.b05 \
        vendor/htc/s4-common/proprietary/etc/firmware/wcnss.mdt:/system/etc/firmware/wcnss.mdt
