# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/hiaeul/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/hiaeul/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/htc/hiaeul/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/htc/hiaeul/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/htc/hiaeul/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/htc/hiaeul/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/htc/hiaeul/proprietary/vendor/bin/tftp_server:system/vendor/bin/tftp_server \
    vendor/htc/hiaeul/proprietary/vendor/lib/hw/gps.default.so:system/vendor/lib/hw/gps.default.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libgps.utils.so:system/vendor/lib/libgps.utils.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libloc_core.so:system/vendor/lib/libloc_core.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libloc_ds_api.so:system/vendor/lib/libloc_ds_api.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libloc_eng.so:system/vendor/lib/libloc_eng.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/hw/gps.default.so:system/vendor/lib64/hw/gps.default.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libgps.utils.so:system/vendor/lib64/libgps.utils.so \
    vendor/htc/hiaeul/proprietary/lib64/libhtc_rilhook.so:system/lib64/libhtc_rilhook.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libloc_api_v02.so:system/vendor/lib64/libloc_api_v02.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libloc_core.so:system/vendor/lib64/libloc_core.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libloc_ds_api.so:system/vendor/lib64/libloc_ds_api.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libloc_eng.so:system/vendor/lib64/libloc_eng.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/librilqmiservices.so:system/vendor/lib64/librilqmiservices.so \
    vendor/htc/hiaeul/proprietary/vendor/bin/qti:system/vendor/bin/qti \
    vendor/htc/hiaeul/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/htc/hiaeul/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libhtc_common.so:system/vendor/lib64/libhtc_common.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqcmaputils.so:system/vendor/lib64/libqcmaputils.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libril-qc-ltedirectdisc.so:system/vendor/lib64/libril-qc-ltedirectdisc.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libsettings.so:system/vendor/lib64/libsettings.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/htc/hiaeul/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/htc/hiaeul/proprietary/vendor/qcril.db:system/vendor/qcril.db
