# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/flounder-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/flounder-common/proprietary/etc/RT5506:system/etc/RT5506 \
    vendor/htc/flounder-common/proprietary/etc/fmas_eq.dat:system/etc/fmas_eq.dat \
    vendor/htc/flounder-common/proprietary/lib/soundfx/libfmas.so:system/lib/soundfx/libfmas.so \
    vendor/htc/flounder-common/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/htc/flounder-common/proprietary/vendor/etc/model_frontal.xml:system/vendor/etc/model_frontal.xml \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/LVVEFS_Rx_Configuration.txt:system/vendor/etc/nxp/LVVEFS_Rx_Configuration.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/LVVEFS_Tx_Configuration.txt:system/vendor/etc/nxp/LVVEFS_Tx_Configuration.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_48000Hz.txt:system/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt:system/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt:system/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_EARPIECE_48000Hz.txt:system/vendor/etc/nxp/Rx_ControlParams_EARPIECE_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_SPEAKER_48000Hz.txt:system/vendor/etc/nxp/Rx_ControlParams_SPEAKER_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_WIRED_HEADPHONE_48000Hz.txt:system/vendor/etc/nxp/Rx_ControlParams_WIRED_HEADPHONE_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_WIRED_HEADSET_48000Hz.txt:system/vendor/etc/nxp/Rx_ControlParams_WIRED_HEADSET_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_16000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_24000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_32000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_48000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_8000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_16000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_24000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_32000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_8000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_16000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_24000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_32000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_8000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_16000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_EARPIECE_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_24000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_EARPIECE_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_32000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_EARPIECE_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_48000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_EARPIECE_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_8000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_EARPIECE_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_16000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_SPEAKER_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_24000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_SPEAKER_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_32000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_SPEAKER_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_48000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_SPEAKER_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_8000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_SPEAKER_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_16000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_24000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_32000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_48000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_8000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_16000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_24000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_32000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_48000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_8000Hz.txt:system/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback.drc:system/vendor/etc/tfa/playback.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback.eq:system/vendor/etc/tfa/playback.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback.preset:system/vendor/etc/tfa/playback.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG.config:system/vendor/etc/tfa/playbackMFG.config \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG.drc:system/vendor/etc/tfa/playbackMFG.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG.eq:system/vendor/etc/tfa/playbackMFG.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG.preset:system/vendor/etc/tfa/playbackMFG.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG_l.config:system/vendor/etc/tfa/playbackMFG_l.config \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG_l.drc:system/vendor/etc/tfa/playbackMFG_l.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG_l.eq:system/vendor/etc/tfa/playbackMFG_l.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG_l.preset:system/vendor/etc/tfa/playbackMFG_l.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback_l.drc:system/vendor/etc/tfa/playback_l.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback_l.eq:system/vendor/etc/tfa/playback_l.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback_l.preset:system/vendor/etc/tfa/playback_l.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895.config:system/vendor/etc/tfa/tfa9895.config \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895.patch:system/vendor/etc/tfa/tfa9895.patch \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895.speaker:system/vendor/etc/tfa/tfa9895.speaker \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895MFG.patch:system/vendor/etc/tfa/tfa9895MFG.patch \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895_l.speaker:system/vendor/etc/tfa/tfa9895_l.speaker \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip.drc:system/vendor/etc/tfa/voip.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip.eq:system/vendor/etc/tfa/voip.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip.preset:system/vendor/etc/tfa/voip.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip_l.drc:system/vendor/etc/tfa/voip_l.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip_l.eq:system/vendor/etc/tfa/voip_l.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip_l.preset:system/vendor/etc/tfa/voip_l.preset \
    vendor/htc/flounder-common/proprietary/vendor/firmware/bcm20795_firmware.ncd:system/vendor/firmware/bcm20795_firmware.ncd \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_aacdec_ucode.bin:system/vendor/firmware/nvavp_aacdec_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_aud_ucode.bin:system/vendor/firmware/nvavp_aud_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_mp3dec_ucode.bin:system/vendor/firmware/nvavp_mp3dec_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_os_0ff00000.bin:system/vendor/firmware/nvavp_os_0ff00000.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_os_8ff00000.bin:system/vendor/firmware/nvavp_os_8ff00000.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_os_eff00000.bin:system/vendor/firmware/nvavp_os_eff00000.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_os_f7e00000.bin:system/vendor/firmware/nvavp_os_f7e00000.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_vid_ucode_alt.bin:system/vendor/firmware/nvavp_vid_ucode_alt.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/rt5677_elf_vad:system/vendor/firmware/rt5677_elf_vad \
    vendor/htc/flounder-common/proprietary/vendor/firmware/sar0_CY8C.img:system/vendor/firmware/sar0_CY8C.img \
    vendor/htc/flounder-common/proprietary/vendor/firmware/sar1_CY8C.img:system/vendor/firmware/sar1_CY8C.img \
    vendor/htc/flounder-common/proprietary/vendor/firmware/sensor_hub.img:system/vendor/firmware/sensor_hub.img \
    vendor/htc/flounder-common/proprietary/vendor/firmware/synaptics.img:system/vendor/firmware/synaptics.img \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/NETB_img.bin:system/vendor/firmware/tegra13x/NETB_img.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/fecs.bin:system/vendor/firmware/tegra13x/fecs.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/gpccs.bin:system/vendor/firmware/tegra13x/gpccs.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/gpmu_ucode.bin:system/vendor/firmware/tegra13x/gpmu_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/nvhost_msenc031.fw:system/vendor/firmware/tegra13x/nvhost_msenc031.fw \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/nvhost_tsec.fw:system/vendor/firmware/tegra13x/nvhost_tsec.fw \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/vic03_ucode.bin:system/vendor/firmware/tegra13x/vic03_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/lib/egl/libEGL_tegra.so:system/vendor/lib/egl/libEGL_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/egl/libGLESv1_CM_tegra.so:system/vendor/lib/egl/libGLESv1_CM_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/egl/libGLESv2_tegra.so:system/vendor/lib/egl/libGLESv2_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/camera.tegra132.so:system/vendor/lib/hw/camera.tegra132.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/gatekeeper.flounder.so:system/vendor/lib/hw/gatekeeper.flounder.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/gralloc.tegra132.so:system/vendor/lib/hw/gralloc.tegra132.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/hwcomposer.tegra132.so:system/vendor/lib/hw/hwcomposer.tegra132.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/keystore.flounder.so:system/vendor/lib/hw/keystore.flounder.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/memtrack.tegra132.so:system/vendor/lib/hw/memtrack.tegra132.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libLifevibes_lvverx.so:system/vendor/lib/libLifevibes_lvverx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libLifevibes_lvvetx.so:system/vendor/lib/libLifevibes_lvvetx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libaudioavp.so:system/vendor/lib/libaudioavp.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libclcore_nvidia.bc:system/vendor/lib/libclcore_nvidia.bc \
    vendor/htc/flounder-common/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libfrsdk.so:system/vendor/lib/libfrsdk.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libglcore.so:system/vendor/lib/libglcore.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libhtcacoustic.so:system/vendor/lib/libhtcacoustic.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvRSCompiler.so:system/vendor/lib/libnvRSCompiler.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvRSDriver.so:system/vendor/lib/libnvRSDriver.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvapputil.so:system/vendor/lib/libnvapputil.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvavp.so:system/vendor/lib/libnvavp.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvblit.so:system/vendor/lib/libnvblit.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcam_imageencoder.so:system/vendor/lib/libnvcam_imageencoder.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcamerahdr.so:system/vendor/lib/libnvcamerahdr.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcapclk.so:system/vendor/lib/libnvcapclk.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcms.so:system/vendor/lib/libnvcms.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcompute.so:system/vendor/lib/libnvcompute.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvddk_2d.so:system/vendor/lib/libnvddk_2d.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvddk_2d_v2.so:system/vendor/lib/libnvddk_2d_v2.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvddk_vic.so:system/vendor/lib/libnvddk_vic.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvfusebypass.so:system/vendor/lib/libnvfusebypass.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvglsi.so:system/vendor/lib/libnvglsi.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvgr.so:system/vendor/lib/libnvgr.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvisp_v3.so:system/vendor/lib/libnvisp_v3.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm.so:system/vendor/lib/libnvmm.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_audio.so:system/vendor/lib/libnvmm_audio.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_camera_v3.so:system/vendor/lib/libnvmm_camera_v3.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_contentpipe.so:system/vendor/lib/libnvmm_contentpipe.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_parser.so:system/vendor/lib/libnvmm_parser.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_utils.so:system/vendor/lib/libnvmm_utils.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_writer.so:system/vendor/lib/libnvmm_writer.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite.so:system/vendor/lib/libnvmmlite.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite_audio.so:system/vendor/lib/libnvmmlite_audio.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite_image.so:system/vendor/lib/libnvmmlite_image.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite_utils.so:system/vendor/lib/libnvmmlite_utils.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite_video.so:system/vendor/lib/libnvmmlite_video.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvodm_query.so:system/vendor/lib/libnvodm_query.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvomx.so:system/vendor/lib/libnvomx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvomxilclient.so:system/vendor/lib/libnvomxilclient.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvos.so:system/vendor/lib/libnvos.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvparser.so:system/vendor/lib/libnvparser.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvptx.so:system/vendor/lib/libnvptx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvrm.so:system/vendor/lib/libnvrm.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvrm_graphics.so:system/vendor/lib/libnvrm_graphics.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvrmapi_tegra.so:system/vendor/lib/libnvrmapi_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvsm.so:system/vendor/lib/libnvsm.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvtnr.so:system/vendor/lib/libnvtnr.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvtvmr.so:system/vendor/lib/libnvtvmr.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvvicsi_v3.so:system/vendor/lib/libnvvicsi_v3.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvwsi.so:system/vendor/lib/libnvwsi.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libopencv24_tegra.so:system/vendor/lib/libopencv24_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libstagefrighthw.so:system/vendor/lib/libstagefrighthw.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libtsechdcp.so:system/vendor/lib/libtsechdcp.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/egl/libEGL_tegra.so:system/vendor/lib64/egl/libEGL_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/egl/libGLESv1_CM_tegra.so:system/vendor/lib64/egl/libGLESv1_CM_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/egl/libGLESv2_tegra.so:system/vendor/lib64/egl/libGLESv2_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libclcore_nvidia.bc:system/vendor/lib64/libclcore_nvidia.bc \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libglcore.so:system/vendor/lib64/libglcore.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvRSCompiler.so:system/vendor/lib64/libnvRSCompiler.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvRSDriver.so:system/vendor/lib64/libnvRSDriver.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvblit.so:system/vendor/lib64/libnvblit.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvcms.so:system/vendor/lib64/libnvcms.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvcompute.so:system/vendor/lib64/libnvcompute.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvddk_2d_v2.so:system/vendor/lib64/libnvddk_2d_v2.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvddk_vic.so:system/vendor/lib64/libnvddk_vic.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvglsi.so:system/vendor/lib64/libnvglsi.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvptx.so:system/vendor/lib64/libnvptx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvrmapi_tegra.so:system/vendor/lib64/libnvrmapi_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvwsi.so:system/vendor/lib64/libnvwsi.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/htc/flounder-common/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/htc/flounder-common/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd

PRODUCT_PACKAGES += \
    HotwordEnrollment
