# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/flounder-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/flounder-common/proprietary/etc/RT5506:system/etc/RT5506 \
    vendor/htc/flounder-common/proprietary/etc/fmas_eq.dat:system/etc/fmas_eq.dat \
    vendor/htc/flounder-common/proprietary/vendor/lib/soundfx/libfmas.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libfmas.so \
    vendor/htc/flounder-common/proprietary/vendor/etc/model_frontal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/model_frontal.xml \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/LVVEFS_Rx_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/LVVEFS_Rx_Configuration.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/LVVEFS_Tx_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/LVVEFS_Tx_Configuration.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_EARPIECE_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_EARPIECE_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_SPEAKER_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_SPEAKER_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_WIRED_HEADPHONE_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_WIRED_HEADPHONE_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Rx_ControlParams_WIRED_HEADSET_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_WIRED_HEADSET_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_16000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_24000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_32000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_48000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_8000Hz.txt \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG.config \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG_l.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG_l.config \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG_l.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG_l.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG_l.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG_l.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playbackMFG_l.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG_l.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback_l.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback_l.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback_l.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback_l.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/playback_l.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback_l.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895.config \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895.patch:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895.patch \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895.speaker:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895.speaker \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895MFG.patch:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895MFG.patch \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/tfa9895_l.speaker:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895_l.speaker \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip.preset \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip_l.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip_l.drc \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip_l.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip_l.eq \
    vendor/htc/flounder-common/proprietary/vendor/etc/tfa/voip_l.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip_l.preset \
    vendor/htc/flounder-common/proprietary/vendor/firmware/bcm20795_firmware.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm20795_firmware.ncd \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_aacdec_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_aacdec_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_aud_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_aud_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_mp3dec_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_mp3dec_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_os_0ff00000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_os_0ff00000.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_os_8ff00000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_os_8ff00000.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_os_eff00000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_os_eff00000.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_os_f7e00000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_os_f7e00000.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/nvavp_vid_ucode_alt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_vid_ucode_alt.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/rt5677_elf_vad:$(TARGET_COPY_OUT_VENDOR)/firmware/rt5677_elf_vad \
    vendor/htc/flounder-common/proprietary/vendor/firmware/sar0_CY8C.img:$(TARGET_COPY_OUT_VENDOR)/firmware/sar0_CY8C.img \
    vendor/htc/flounder-common/proprietary/vendor/firmware/sar1_CY8C.img:$(TARGET_COPY_OUT_VENDOR)/firmware/sar1_CY8C.img \
    vendor/htc/flounder-common/proprietary/vendor/firmware/sensor_hub.img:$(TARGET_COPY_OUT_VENDOR)/firmware/sensor_hub.img \
    vendor/htc/flounder-common/proprietary/vendor/firmware/synaptics.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics.img \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/NETB_img.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/NETB_img.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/fecs.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/fecs.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/gpccs.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/gpccs.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/gpmu_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/gpmu_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/nvhost_msenc031.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/nvhost_msenc031.fw \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/nvhost_tsec.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/nvhost_tsec.fw \
    vendor/htc/flounder-common/proprietary/vendor/firmware/tegra13x/vic03_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/vic03_ucode.bin \
    vendor/htc/flounder-common/proprietary/vendor/lib/egl/libEGL_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/egl/libGLESv1_CM_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/egl/libGLESv2_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/camera.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.tegra132.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/gatekeeper.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.flounder.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/gralloc.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.tegra132.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/hwcomposer.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.tegra132.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/keystore.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.flounder.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/hw/memtrack.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.tegra132.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/soundfx/libLifevibes_lvverx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libLifevibes_lvverx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/soundfx/libLifevibes_lvvetx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libLifevibes_lvvetx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L1.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libaudioavp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioavp.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libclcore_nvidia.bc:$(TARGET_COPY_OUT_VENDOR)/lib/libclcore_nvidia.bc \
    vendor/htc/flounder-common/proprietary/vendor/lib/libdrmdecrypt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmdecrypt.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfrsdk.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libglcore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libglcore.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libhtcacoustic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhtcacoustic.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvRSCompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvRSCompiler.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvRSDriver.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvRSDriver.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvapputil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvapputil.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvavp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvavp.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvblit.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvblit.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcam_imageencoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcam_imageencoder.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcamerahdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcamerahdr.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcapclk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcapclk.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcms.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcms.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvcompute.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcompute.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvddk_2d.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvddk_2d.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvddk_2d_v2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvddk_2d_v2.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvddk_vic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvddk_vic.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvfusebypass.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvfusebypass.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvglsi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvglsi.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvgr.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvisp_v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvisp_v3.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_audio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_audio.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_camera_v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_camera_v3.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_contentpipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_contentpipe.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_parser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_parser.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_utils.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmm_writer.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_writer.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite_audio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite_audio.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite_image.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite_image.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite_utils.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvmmlite_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite_video.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvodm_query.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvodm_query.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvomx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvomx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvomxilclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvomxilclient.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvos.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvos.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvparser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvparser.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvptx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvptx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvrm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvrm.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvrm_graphics.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvrm_graphics.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvrmapi_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvrmapi_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvsm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvsm.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvtnr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvtnr.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvtvmr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvtvmr.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvvicsi_v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvvicsi_v3.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libnvwsi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvwsi.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libopencv24_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/libopencv24_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrighthw.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libtsechdcp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtsechdcp.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L1.so \
    vendor/htc/flounder-common/proprietary/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvm.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/egl/libEGL_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/egl/libGLESv1_CM_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/egl/libGLESv2_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libclcore_nvidia.bc:$(TARGET_COPY_OUT_VENDOR)/lib64/libclcore_nvidia.bc \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libglcore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libglcore.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvRSCompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvRSCompiler.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvRSDriver.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvRSDriver.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvblit.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvblit.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvcms.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvcms.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvcompute.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvcompute.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvddk_2d_v2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvddk_2d_v2.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvddk_vic.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvddk_vic.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvglsi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvglsi.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvptx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvptx.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvrmapi_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvrmapi_tegra.so \
    vendor/htc/flounder-common/proprietary/vendor/lib64/libnvwsi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvwsi.so \
    vendor/htc/flounder-common/proprietary/vendor/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd \
    vendor/htc/flounder-common/proprietary/vendor/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd

PRODUCT_PACKAGES += \
    HotwordEnrollment
