# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/liberty/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/liberty/proprietary/libcamera.so:obj/lib/libcamera.so
 
# All the blobs necessary for passion
PRODUCT_COPY_FILES += \
    vendor/htc/liberty/proprietary/akmd:/system/bin/akmd \
    vendor/htc/liberty/proprietary/AudioFilter.csv:/system/etc/AudioFilter.csv \
    vendor/htc/liberty/proprietary/AudioPara4.csv:/system/etc/AudioPara4.csv \
    vendor/htc/liberty/proprietary/AudioPara4_WB.csv:/system/etc/AudioPara4_WB.csv \
    vendor/htc/liberty/proprietary/AudioPreProcess.csv:/system/etc/AudioPreProcess.csv \
    vendor/htc/liberty/proprietary/WPDB.zip:/system/etc/WPDB.zip \
    vendor/htc/liberty/proprietary/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
    vendor/htc/liberty/proprietary/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw \
    vendor/htc/liberty/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/liberty/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/liberty/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/liberty/proprietary/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/htc/liberty/proprietary/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/htc/liberty/proprietary/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/htc/liberty/proprietary/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/htc/liberty/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/liberty/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/liberty/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/liberty/proprietary/libaudioeq.so:/system/lib/libaudioeq.so \
    vendor/htc/liberty/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/liberty/proprietary/liboemcamera.so:/system/lib/liboemcamera.so

