# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/hero/extract-files.sh

PRODUCT_COPY_FILES := \
    vendor/htc/hero/proprietary/libgps.so:obj/lib/libgps.so \
    vendor/htc/hero/proprietary/libcamera.so:obj/lib/libcamera.so

PRODUCT_COPY_FILES += \
    vendor/htc/hero/proprietary/akmd:system/bin/akmd \
    vendor/htc/hero/proprietary/01_qcomm_omx.cfg:system/etc/01_qcomm_omx.cfg \
    vendor/htc/hero/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/htc/hero/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv \
    vendor/htc/hero/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
    vendor/htc/hero/proprietary/avpr.bts:system/etc/firmware/avpr.bts \
    vendor/htc/hero/proprietary/brf6300.bin:system/etc/firmware/brf6300.bin \
    vendor/htc/hero/proprietary/brf6350.bin:system/etc/firmware/brf6350.bin \
    vendor/htc/hero/proprietary/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    vendor/htc/hero/proprietary/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/htc/hero/proprietary/tiinit_5.3.53.bts:system/etc/firmware/tiinit_5.3.53.bts \
    vendor/htc/hero/proprietary/vac_config.ini:system/etc/firmware/vac_config.ini \
    vendor/htc/hero/proprietary/Fw1251r1c.bin:system/etc/wifi/Fw1251r1c.bin \
    vendor/htc/hero/proprietary/libGLES_qcom.so:system/lib/egl/libGLES_qcom.so \
	vendor/htc/hero/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/htc/hero/proprietary/libgps.so:system/lib/libgps.so \
    vendor/htc/hero/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    vendor/htc/hero/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \
    vendor/htc/hero/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/hero/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/hero/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/htc/hero/proprietary/libOmxCore.so:system/lib/libOmxCore.so \
    vendor/htc/hero/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/htc/hero/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/htc/hero/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \

ifdef WITH_WINDOWS_MEDIA
PRODUCT_COPY_FILES += \
    vendor/htc/hero/proprietary/libomx_wmadec_sharedlibrary.so:system/lib/libomx_wmadec_sharedlibrary.so \
    vendor/htc/hero/proprietary/libomx_wmvdec_sharedlibrary.so:system/lib/libomx_wmvdec_sharedlibrary.so \
    vendor/htc/hero/proprietary/libpvasfcommon.so:system/lib/libpvasfcommon.so \
    vendor/htc/hero/proprietary/libpvasflocalpbreg.so:system/lib/libpvasflocalpbreg.so \
    vendor/htc/hero/proprietary/libpvasflocalpb.so:system/lib/libpvasflocalpb.so \
    vendor/htc/hero/proprietary/pvasflocal.cfg:system/etc/pvasflocal.cfg
endif

