# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/jewel/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/htc/jewel/proprietary/lib/libchromatix_s5k3h2yx_default_video.so:/system/lib/libchromatix_s5k3h2yx_default_video.so \
        vendor/htc/jewel/proprietary/lib/libchromatix_s5k3h2yx_hdr.so:/system/lib/libchromatix_s5k3h2yx_hdr.so \
        vendor/htc/jewel/proprietary/lib/libchromatix_s5k3h2yx_hfr.so:/system/lib/libchromatix_s5k3h2yx_hfr.so \
        vendor/htc/jewel/proprietary/lib/libchromatix_s5k3h2yx_preview.so:/system/lib/libchromatix_s5k3h2yx_preview.so \
        vendor/htc/jewel/proprietary/lib/libchromatix_s5k3h2yx_zsl.so:/system/lib/libchromatix_s5k3h2yx_zsl.so \
        vendor/htc/jewel/proprietary/lib/libchromatix_s5k6a1gx_default_video.so:/system/lib/libchromatix_s5k6a1gx_default_video.so \
        vendor/htc/jewel/proprietary/lib/libchromatix_s5k6a1gx_preview.so:/system/lib/libchromatix_s5k6a1gx_preview.so \
        vendor/htc/jewel/proprietary/lib/libchromatix_s5k6a1gx_zsl.so:/system/lib/libchromatix_s5k6a1gx_zsl.so \
        vendor/htc/jewel/proprietary/lib/hw/nfc.default.so:/system/lib/hw/nfc.default.so \
        vendor/htc/jewel/proprietary/vendor/firmware/libpn544_fw.so:/system/vendor/firmware/libpn544_fw.so \
        vendor/htc/jewel/proprietary/lib/libhtc_rilhook.so:/system/lib/libhtc_rilhook.so \
        vendor/htc/jewel/proprietary/lib/hw/sensors.default.so:/system/lib/hw/sensors.default.so \
        vendor/htc/jewel/proprietary/lib/libimu.so:/system/lib/libimu.so \
        vendor/htc/jewel/proprietary/lib/libmlplatform.so:/system/lib/libmlplatform.so \
        vendor/htc/jewel/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
        vendor/htc/jewel/proprietary/lib/libmpl.so:/system/lib/libmpl.so \
        vendor/htc/jewel/proprietary/bin/qmuxd:/system/bin/qmuxd \
        vendor/htc/jewel/proprietary/etc/firmware/modem.b00:/system/etc/firmware/modem.b00 \
        vendor/htc/jewel/proprietary/etc/firmware/modem.b01:/system/etc/firmware/modem.b01 \
        vendor/htc/jewel/proprietary/etc/firmware/modem.b02:/system/etc/firmware/modem.b02 \
        vendor/htc/jewel/proprietary/etc/firmware/modem.b03:/system/etc/firmware/modem.b03 \
        vendor/htc/jewel/proprietary/etc/firmware/modem.b04:/system/etc/firmware/modem.b04 \
        vendor/htc/jewel/proprietary/etc/firmware/modem.b06:/system/etc/firmware/modem.b06 \
        vendor/htc/jewel/proprietary/etc/firmware/modem.b07:/system/etc/firmware/modem.b07 \
        vendor/htc/jewel/proprietary/etc/firmware/modem.mdt:/system/etc/firmware/modem.mdt \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b00:/system/etc/firmware/modem_fw.b00 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b01:/system/etc/firmware/modem_fw.b01 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b02:/system/etc/firmware/modem_fw.b02 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b03:/system/etc/firmware/modem_fw.b03 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b04:/system/etc/firmware/modem_fw.b04 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b05:/system/etc/firmware/modem_fw.b05 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b06:/system/etc/firmware/modem_fw.b06 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b07:/system/etc/firmware/modem_fw.b07 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b08:/system/etc/firmware/modem_fw.b08 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b09:/system/etc/firmware/modem_fw.b09 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b10:/system/etc/firmware/modem_fw.b10 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b13:/system/etc/firmware/modem_fw.b13 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b14:/system/etc/firmware/modem_fw.b14 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b21:/system/etc/firmware/modem_fw.b21 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b22:/system/etc/firmware/modem_fw.b22 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b23:/system/etc/firmware/modem_fw.b23 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b25:/system/etc/firmware/modem_fw.b25 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b26:/system/etc/firmware/modem_fw.b26 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.b29:/system/etc/firmware/modem_fw.b29 \
        vendor/htc/jewel/proprietary/etc/firmware/modem_fw.mdt:/system/etc/firmware/modem_fw.mdt \
        vendor/htc/jewel/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
        vendor/htc/jewel/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
        vendor/htc/jewel/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
        vendor/htc/jewel/proprietary/lib/libidl.so:/system/lib/libidl.so \
        vendor/htc/jewel/proprietary/lib/libqdi.so:/system/lib/libqdi.so \
        vendor/htc/jewel/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
        vendor/htc/jewel/proprietary/lib/libqmi_cci.so:/system/lib/libqmi_cci.so \
        vendor/htc/jewel/proprietary/lib/libqmi_common_so.so:/system/lib/libqmi_common_so.so \
        vendor/htc/jewel/proprietary/lib/libqmi_csi.so:/system/lib/libqmi_csi.so \
        vendor/htc/jewel/proprietary/lib/libqmi_encdec.so:/system/lib/libqmi_encdec.so \
        vendor/htc/jewel/proprietary/lib/libqmiservices.so:/system/lib/libqmiservices.so \
        vendor/htc/jewel/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
        vendor/htc/jewel/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
        vendor/htc/jewel/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so
