# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/click/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/click/proprietary/libgps.so:obj/lib/libgps.so

# proprietary firmware files
PRODUCT_COPY_FILES += \
    vendor/htc/click/proprietary/firmware/Fw1251r1c.bin:system/etc/wifi/Fw1251r1c.bin \
    vendor/htc/click/proprietary/firmware/brf6300.bin:system/etc/firmware/brf6300.bin \
    vendor/htc/click/proprietary/firmware/brf6350.bin:system/etc/firmware/brf6350.bin

# All the blobs necessary for click
PRODUCT_COPY_FILES += \
    vendor/htc/click/proprietary/HTCCalibrate.apk:system/app/HTCCalibrate.apk \
    vendor/htc/click/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv \
    vendor/htc/click/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/htc/click/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
    vendor/htc/click/proprietary/libmmcamera.so:system/lib/libmmcamera.so \
    vendor/htc/click/proprietary/libmm-qcamera-tgt.so:system/lib/libmm-qcamera-tgt.so \
    vendor/htc/click/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/htc/click/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/htc/click/proprietary/libqcamera.so:system/lib/libqcamera.so \
    vendor/htc/click/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/click/proprietary/libgps.so:system/lib/libgps.so \
    vendor/htc/click/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/htc/click/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/htc/click/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/htc/click/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/click/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    vendor/htc/click/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \
    vendor/htc/click/proprietary/akm8973:system/bin/akm8973
