# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/buzz/extract-files.sh


# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    	device/htc/buzz/custom/logo.rle:root/logo.rle \
    	vendor/htc/buzz/proprietary/libgps.so:obj/lib/libgps.so \
    	vendor/htc/buzz/proprietary/libcamera.so:obj/lib/libcamera.so \
        device/htc/buzz/kernel:out/target/product/buzz/kernel

# proprietary stuff
PRODUCT_COPY_FILES += \
	vendor/htc/buzz/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv \
	vendor/htc/buzz/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
	vendor/htc/buzz/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
	vendor/htc/buzz/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
	vendor/htc/buzz/proprietary/libgps.so:system/lib/libgps.so \
	vendor/htc/buzz/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
	vendor/htc/buzz/proprietary/libcamera.so:system/lib/libcamera.so \
	vendor/htc/buzz/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
	vendor/htc/buzz/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
	vendor/htc/buzz/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
	vendor/htc/buzz/proprietary/libOmxCore.so:system/lib/libOmxCore.so \
	vendor/htc/buzz/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    	vendor/htc/buzz/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    	vendor/htc/buzz/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \
    	vendor/htc/buzz/proprietary/buzz-keypad.kl:system/usr/keylayout/buzz-keypad.kl \
    	vendor/htc/buzz/proprietary/h2w_headset.kl:system/usr/keylayout/h2w_headset.kl \
    	vendor/htc/buzz/proprietary/qwerty.kl:system/usr/keylayout/qwerty.kl \
	vendor/htc/buzz/proprietary/agps_rm:system/etc/agps_rm \
	vendor/htc/buzz/proprietary/libt9.so:system/lib/libt9.so \
	vendor/htc/buzz/proprietary/voicemail-conf.xml:system/etc/voicemail-conf.xml \
	vendor/htc/buzz/proprietary/spn-conf.xml:system/etc/spn-conf.xml \
	vendor/htc/buzz/proprietary/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
	vendor/htc/buzz/proprietary/libpvasfcommon.so:system/lib/libpvasfcommon.so \
	vendor/htc/buzz/proprietary/libpvasflocalpb.so:system/lib/libpvasflocalpb.so \
	vendor/htc/buzz/proprietary/libpvasflocalpbreg.so:system/lib/libpvasflocalpbreg.so \
	vendor/htc/buzz/proprietary/pvasflocal.cfg:system/etc/pvasflocal.cfg \
	vendor/htc/buzz/proprietary/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	vendor/htc/buzz/proprietary/akmd:system/bin/akmd \
	vendor/htc/buzz/proprietary/qwerty2.kcm.bin:system/usr/keychars/qwerty2.kcm.bin \
	vendor/htc/buzz/proprietary/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \
	device/htc/buzz/firmware/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
	device/htc/buzz/firmware/fw_bcm4329.bin:system/etc/firmware/fw_bcm4329.bin \
	device/htc/buzz/firmware/fw_bcm4329_apsta.bin:system/etc/firmware/fw_bcm4329_apsta.bin

