# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/flounder_lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libnvodm_imager.so:system/vendor/lib/libnvodm_imager.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/gatekeeper.flounder.so:system/vendor/lib64/hw/gatekeeper.flounder.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/gralloc.tegra132.so:system/vendor/lib64/hw/gralloc.tegra132.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/hwcomposer.tegra132.so:system/vendor/lib64/hw/hwcomposer.tegra132.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/keystore.flounder.so:system/vendor/lib64/hw/keystore.flounder.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/memtrack.tegra132.so:system/vendor/lib64/hw/memtrack.tegra132.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libfrsdk.so:system/vendor/lib64/libfrsdk.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libhtcacoustic.so:system/vendor/lib64/libhtcacoustic.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvapputil.so:system/vendor/lib64/libnvapputil.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvgr.so:system/vendor/lib64/libnvgr.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvos.so:system/vendor/lib64/libnvos.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvrm.so:system/vendor/lib64/libnvrm.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvrm_graphics.so:system/vendor/lib64/libnvrm_graphics.so
PRODUCT_COPY_FILES += \
    vendor/htc/flounder_lte/proprietary/vendor/bin/ATFWD-daemon:system/vendor/bin/ATFWD-daemon \
    vendor/htc/flounder_lte/proprietary/vendor/bin/PktRspTest:system/vendor/bin/PktRspTest \
    vendor/htc/flounder_lte/proprietary/vendor/bin/bridgemgrd:system/vendor/bin/bridgemgrd \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_callback_client:system/vendor/bin/diag_callback_client \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_dci_sample:system/vendor/bin/diag_dci_sample \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_klog:system/vendor/bin/diag_klog \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_mdlog:system/vendor/bin/diag_mdlog \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_qshrink4_daemon:system/vendor/bin/diag_qshrink4_daemon \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_socket_log:system/vendor/bin/diag_socket_log \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_uart_log:system/vendor/bin/diag_uart_log \
    vendor/htc/flounder_lte/proprietary/vendor/bin/ds_fmc_appd:system/vendor/bin/ds_fmc_appd \
    vendor/htc/flounder_lte/proprietary/vendor/bin/dsdnsutil:system/vendor/bin/dsdnsutil \
    vendor/htc/flounder_lte/proprietary/vendor/bin/efsks:system/vendor/bin/efsks \
    vendor/htc/flounder_lte/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/htc/flounder_lte/proprietary/vendor/bin/ks:system/vendor/bin/ks \
    vendor/htc/flounder_lte/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/htc/flounder_lte/proprietary/vendor/bin/nl_listener:system/vendor/bin/nl_listener \
    vendor/htc/flounder_lte/proprietary/vendor/bin/port-bridge:system/vendor/bin/port-bridge \
    vendor/htc/flounder_lte/proprietary/vendor/bin/qcks:system/vendor/bin/qcks \
    vendor/htc/flounder_lte/proprietary/vendor/bin/qmiproxy:system/vendor/bin/qmiproxy \
    vendor/htc/flounder_lte/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/htc/flounder_lte/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/htc/flounder_lte/proprietary/vendor/bin/test_diag:system/vendor/bin/test_diag \
    vendor/htc/flounder_lte/proprietary/vendor/bin/time_daemon:system/vendor/bin/time_daemon \
    vendor/htc/flounder_lte/proprietary/vendor/bin/usbhub:system/vendor/bin/usbhub \
    vendor/htc/flounder_lte/proprietary/vendor/bin/usbhub_init:system/vendor/bin/usbhub_init \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/apps.mbn:system/vendor/firmware/mdm/image/apps.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/dsp1.mbn:system/vendor/firmware/mdm/image/dsp1.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccdma.mbn:system/vendor/firmware/mdm/image/htccdma.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv.mbn:system/vendor/firmware/mdm/image/htccnv.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_a.mbn:system/vendor/firmware/mdm/image/htccnv_a.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_o.mbn:system/vendor/firmware/mdm/image/htccnv_o.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_s.mbn:system/vendor/firmware/mdm/image/htccnv_s.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_t.mbn:system/vendor/firmware/mdm/image/htccnv_t.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_u.mbn:system/vendor/firmware/mdm/image/htccnv_u.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_v.mbn:system/vendor/firmware/mdm/image/htccnv_v.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htcnvmfg.mbn:system/vendor/firmware/mdm/image/htcnvmfg.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htcrfnv.mbn:system/vendor/firmware/mdm/image/htcrfnv.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htcssmem.mbn:system/vendor/firmware/mdm/image/htcssmem.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htcuserd.mbn:system/vendor/firmware/mdm/image/htcuserd.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/mba.mbn:system/vendor/firmware/mdm/image/mba.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_att.img:system/vendor/firmware/mdm/image/rcdata_att.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_o2.img:system/vendor/firmware/mdm/image/rcdata_o2.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_tmo.img:system/vendor/firmware/mdm/image/rcdata_tmo.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_ul.img:system/vendor/firmware/mdm/image/rcdata_ul.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_vzw.img:system/vendor/firmware/mdm/image/rcdata_vzw.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rpm.mbn:system/vendor/firmware/mdm/image/rpm.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/sbl1.mbn:system/vendor/firmware/mdm/image/sbl1.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/sdi.mbn:system/vendor/firmware/mdm/image/sdi.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/tz.mbn:system/vendor/firmware/mdm/image/tz.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/radiover.cfg:system/vendor/firmware/mdm/radiover.cfg \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdsucsd.so:system/vendor/lib/libdsucsd.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libhtc_common.so:system/vendor/lib/libhtc_common.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/librmnetctl.so:system/vendor/lib/librmnetctl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libCommandSvc.so:system/vendor/lib64/libCommandSvc.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdsucsd.so:system/vendor/lib64/libdsucsd.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libhtc_common.so:system/vendor/lib64/libhtc_common.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_csvt_srvc.so:system/vendor/lib64/libqmi_csvt_srvc.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/librmnetctl.so:system/vendor/lib64/librmnetctl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so
