# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/flounder_lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/gatekeeper.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.flounder.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/gralloc.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.tegra132.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/hwcomposer.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/hwcomposer.tegra132.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/keystore.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.flounder.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/memtrack.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/memtrack.tegra132.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfrsdk.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libhtcacoustic.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhtcacoustic.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvapputil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvapputil.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvgr.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvos.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvos.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvrm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvrm.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnvrm_graphics.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvrm_graphics.so
PRODUCT_COPY_FILES += \
    vendor/htc/flounder_lte/proprietary/etc/SuplRootCert:system/etc/SuplRootCert \
    vendor/htc/flounder_lte/proprietary/vendor/lib/hw/gps.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.default.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgeofence.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libgps.utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgps.utils.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libloc_api_v02.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_api_v02.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libloc_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_core.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libloc_ds_api.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_ds_api.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libloc_eng.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_eng.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/hw/gps.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gps.default.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgeofence.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libgps.utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgps.utils.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libloc_api_v02.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_api_v02.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libloc_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_core.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libloc_ds_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_ds_api.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libloc_eng.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_eng.so \
    vendor/htc/flounder_lte/proprietary/vendor/bin/ATFWD-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/ATFWD-daemon \
    vendor/htc/flounder_lte/proprietary/vendor/bin/PktRspTest:$(TARGET_COPY_OUT_VENDOR)/bin/PktRspTest \
    vendor/htc/flounder_lte/proprietary/vendor/bin/bridgemgrd:$(TARGET_COPY_OUT_VENDOR)/bin/bridgemgrd \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_callback_client:$(TARGET_COPY_OUT_VENDOR)/bin/diag_callback_client \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_dci_sample:$(TARGET_COPY_OUT_VENDOR)/bin/diag_dci_sample \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_klog:$(TARGET_COPY_OUT_VENDOR)/bin/diag_klog \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_mdlog:$(TARGET_COPY_OUT_VENDOR)/bin/diag_mdlog \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_qshrink4_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/diag_qshrink4_daemon \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_socket_log:$(TARGET_COPY_OUT_VENDOR)/bin/diag_socket_log \
    vendor/htc/flounder_lte/proprietary/vendor/bin/diag_uart_log:$(TARGET_COPY_OUT_VENDOR)/bin/diag_uart_log \
    vendor/htc/flounder_lte/proprietary/vendor/bin/ds_fmc_appd:$(TARGET_COPY_OUT_VENDOR)/bin/ds_fmc_appd \
    vendor/htc/flounder_lte/proprietary/vendor/bin/dsdnsutil:$(TARGET_COPY_OUT_VENDOR)/bin/dsdnsutil \
    vendor/htc/flounder_lte/proprietary/vendor/bin/efsks:$(TARGET_COPY_OUT_VENDOR)/bin/efsks \
    vendor/htc/flounder_lte/proprietary/vendor/bin/irsc_util:$(TARGET_COPY_OUT_VENDOR)/bin/irsc_util \
    vendor/htc/flounder_lte/proprietary/vendor/bin/ks:$(TARGET_COPY_OUT_VENDOR)/bin/ks \
    vendor/htc/flounder_lte/proprietary/vendor/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    vendor/htc/flounder_lte/proprietary/vendor/bin/nl_listener:$(TARGET_COPY_OUT_VENDOR)/bin/nl_listener \
    vendor/htc/flounder_lte/proprietary/vendor/bin/port-bridge:$(TARGET_COPY_OUT_VENDOR)/bin/port-bridge \
    vendor/htc/flounder_lte/proprietary/vendor/bin/qcks:$(TARGET_COPY_OUT_VENDOR)/bin/qcks \
    vendor/htc/flounder_lte/proprietary/vendor/bin/qmiproxy:$(TARGET_COPY_OUT_VENDOR)/bin/qmiproxy \
    vendor/htc/flounder_lte/proprietary/vendor/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    vendor/htc/flounder_lte/proprietary/vendor/bin/radish:$(TARGET_COPY_OUT_VENDOR)/bin/radish \
    vendor/htc/flounder_lte/proprietary/vendor/bin/test_diag:$(TARGET_COPY_OUT_VENDOR)/bin/test_diag \
    vendor/htc/flounder_lte/proprietary/vendor/bin/time_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/time_daemon \
    vendor/htc/flounder_lte/proprietary/vendor/bin/usbhub:$(TARGET_COPY_OUT_VENDOR)/bin/usbhub \
    vendor/htc/flounder_lte/proprietary/vendor/bin/usbhub_init:$(TARGET_COPY_OUT_VENDOR)/bin/usbhub_init \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/apps.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/apps.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/dsp1.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/dsp1.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccdma.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htccdma.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htccnv.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_a.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htccnv_a.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_o.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htccnv_o.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_s.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htccnv_s.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_t.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htccnv_t.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_u.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htccnv_u.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htccnv_v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htccnv_v.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htcnvmfg.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htcnvmfg.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htcrfnv.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htcrfnv.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htcssmem.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htcssmem.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/htcuserd.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/htcuserd.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/mba.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/mba.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_att.img:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/rcdata_att.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_o2.img:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/rcdata_o2.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_tmo.img:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/rcdata_tmo.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_ul.img:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/rcdata_ul.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rcdata_vzw.img:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/rcdata_vzw.img \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/rpm.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/rpm.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/sbl1.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/sbl1.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/sdi.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/sdi.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/image/tz.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/image/tz.mbn \
    vendor/htc/flounder_lte/proprietary/vendor/firmware/mdm/radiover.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/mdm/radiover.cfg \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libCommandSvc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCommandSvc.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libconfigdb.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdsnetutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsnetutils.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdsucsd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsucsd.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libhtc_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhtc_common.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperipheral_client.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_csvt_srvc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csvt_srvc.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/librmnetctl.so:$(TARGET_COPY_OUT_VENDOR)/lib/librmnetctl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtime_genoff.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libCommandSvc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCommandSvc.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libconfigdb.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdiag.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsi_netctrl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdsnetutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsnetutils.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdsucsd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsucsd.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsutils.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libhtc_common.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhtc_common.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libidl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdmdetect.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperipheral_client.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcci_legacy.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdp.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_cci.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_qmux.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_common_so.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_csi.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_csvt_srvc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_csvt_srvc.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_encdec.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmiservices.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-qmi-1.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qcril-hook-oem.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/librmnetctl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librmnetctl.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtime_genoff.so \
    vendor/htc/flounder_lte/proprietary/vendor/lib64/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxml.so
