# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/espresso/extract-files.sh

PRODUCT_COPY_FILES := \
    vendor/htc/espresso/proprietary/libcamera.so:obj/lib/libcamera.so

PRODUCT_COPY_FILES += \
    vendor/htc/espresso/proprietary/MS-HTCVISION-KNT20-02.apk:system/app/MS-HTCVISION-KNT20-02.apk \
    vendor/htc/espresso/proprietary/akmd:system/bin/akmd \
    vendor/htc/espresso/proprietary/wl1271.bin:system/etc/firmware/wl1271.bin \
    vendor/htc/espresso/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/htc/espresso/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/htc/espresso/proprietary/Fw1273_CHIP.bin:system/etc/wifi/Fw1273_CHIP.bin \
    vendor/htc/espresso/proprietary/Fw1273_CHIP_AP.bin:system/etc/wifi/Fw1273_CHIP_AP.bin \
    vendor/htc/espresso/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv \
    vendor/htc/espresso/proprietary/AudioPara4_WB.csv:system/etc/AudioPara4_WB.csv \
    vendor/htc/espresso/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/htc/espresso/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
    vendor/htc/espresso/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/espresso/proprietary/libganril.so:system/lib/libganril.so \
    vendor/htc/espresso/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/espresso/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/espresso/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/htc/espresso/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/htc/espresso/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    vendor/htc/espresso/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \
    vendor/htc/espresso/proprietary/libkineto.so:system/lib/libkineto.so \
    vendor/htc/espresso/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/espresso/proprietary/libmmclient.so:system/lib/libmmclient.so \
    vendor/htc/espresso/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/htc/espresso/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/espresso/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/htc/espresso/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/htc/espresso/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/htc/espresso/proprietary/librilswitch.so:system/lib/librilswitch.so

