# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/espresso/extract-files.sh

# remove once .34 is ported
PRODUCT_COPY_FILES += \
    vendor/htc/espresso/proprietary/gralloc.msm7k.so:/system/lib/hw/gralloc.msm7k.so

PRODUCT_COPY_FILES := \
    vendor/htc/espresso/proprietary/libgps.so:obj/lib/libgps.so

PRODUCT_COPY_FILES += \
    vendor/htc/espresso/proprietary/akmd:system/bin/akmd \
    vendor/htc/espresso/proprietary/01_qcomm_omx.cfg:system/etc/01_qcomm_omx.cfg \
    vendor/htc/espresso/proprietary/wl1271.bin:system/etc/firmware/wl1271.bin \
    vendor/htc/espresso/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv \
    vendor/htc/espresso/proprietary/AudioPara4_WB.csv:system/etc/AudioPara4_WB.csv \
    vendor/htc/espresso/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/htc/espresso/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
    vendor/htc/espresso/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/espresso/proprietary/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/htc/espresso/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/espresso/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/espresso/proprietary/libgps.so:system/lib/libgps.so \
    vendor/htc/espresso/proprietary/T-Mobile_USA_Intermediate_CA_01.der:system/etc/T-Mobile_USA_Intermediate_CA_01.der \
    vendor/htc/espresso/proprietary/T-Mobile_USA_Issuer_CA_01.der:system/etc/T-Mobile_USA_Issuer_CA_01.der \
    vendor/htc/espresso/proprietary/T-Mobile_USA_Issuer_CA_02.der:system/etc/T-Mobile_USA_Issuer_CA_02.de \
    vendor/htc/espresso/proprietary/T-Mobile_USA_Root_CA.der:system/etc/T-Mobile_USA_Root_CA.der \
    vendor/htc/espresso/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/htc/espresso/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    vendor/htc/espresso/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so \
    vendor/htc/espresso/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/espresso/proprietary/libmmclient.so:system/lib/libmmclient.so \
    vendor/htc/espresso/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/htc/espresso/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/htc/espresso/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/htc/espresso/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/htc/espresso/proprietary/libspeech.so:system/lib/libspeech.so \
    vendor/htc/espresso/proprietary/pvasflocal.cfg:system/etc/pvasflocal.cfg \
    vendor/htc/espresso/proprietary/libomx_wmadec_sharedlibrary.so:system/lib/libomx_wmadec_sharedlibrary.so \
    vendor/htc/espresso/proprietary/libomx_wmvdec_sharedlibrary.so:system/lib/libomx_wmvdec_sharedlibrary.so \
    vendor/htc/espresso/proprietary/libpvasfcommon.so:system/lib/libpvasfcommon.so \
    vendor/htc/espresso/proprietary/libpvasflocalpbreg.so:system/lib/libpvasflocalpbreg.so \
    vendor/htc/espresso/proprietary/libpvasflocalpb.so:system/lib/libpvasflocalpb.so \
    vendor/htc/espresso/proprietary/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
    vendor/htc/espresso/proprietary/sensors.espresso.so:system/lib/hw/sensors.espresso.so \
    vendor/htc/espresso/proprietary/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/htc/espresso/proprietary/curcial-oj.kl:system/usr/keylayout/curcial-oj.kl

