# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/glacier/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/glacier/proprietary/libloc_api.so:obj/lib/libloc_api.so \
    vendor/htc/glacier/proprietary/libloc_api-rpc.so:obj/lib/libloc_api-rpc.so \
    vendor/htc/glacier/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/glacier/proprietary/libaudio.so:obj/lib/libaudio.so \
    vendor/htc/glacier/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so

# All the blobs necessary for passion
PRODUCT_COPY_FILES += \
    vendor/htc/glacier/proprietary/A1026_CFG.csv:/system/etc/A1026_CFG.csv \
    vendor/htc/glacier/proprietary/AdieHWCodec.csv:/system/etc/AdieHWCodec.csv \
    vendor/htc/glacier/proprietary/AdieHWCodec_WA.csv:/system/etc/AdieHWCodec_WA.csv \
    vendor/htc/glacier/proprietary/agps_rm:/system/etc/agps_rm \
    vendor/htc/glacier/proprietary/akmd:/system/bin/akmd \
    vendor/htc/glacier/proprietary/AudioBTID.csv:/system/etc/AudioBTID.csv \
    vendor/htc/glacier/proprietary/awb_camera:/system/bin/awb_camera \
    vendor/htc/glacier/proprietary/BCM4329B1_002.002.023.0511.0538.hcd:/system/etc/firmware/BCM4329B1_002.002.023.0511.0538.hcd \
    vendor/htc/glacier/proprietary/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/glacier/proprietary/default.acdb:/system/etc/firmware/default.acdb \
    vendor/htc/glacier/proprietary/default_org.acdb:/system/etc/firmware/default_org.acdb \
    vendor/htc/glacier/proprietary/default_org_WA.acdb:/system/etc/firmware/default_org_WA.acdb \
    vendor/htc/glacier/proprietary/fw_bcm4329_apsta.bin:/system/etc/firmware/fw_bcm4329_apsta.bin \
    vendor/htc/glacier/proprietary/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/glacier/proprietary/gralloc.msm7x30.so:/system/lib/hw/gralloc.msm7x30.so \
    vendor/htc/glacier/proprietary/sensors.glacier.so:/system/lib/hw/sensors.glacier.so \
    vendor/htc/glacier/proprietary/libaudio.so:/system/lib/libaudio.so \
    vendor/htc/glacier/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/glacier/proprietary/libaudioeq.so:/system/lib/libaudioeq.so \
    vendor/htc/glacier/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/glacier/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/glacier/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/glacier/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/glacier/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/glacier/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/glacier/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/glacier/proprietary/libHTC_mm_property.so:/system/lib/libHTC_mm_property.so \
    vendor/htc/glacier/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/glacier/proprietary/libganril.so:/system/lib/libganril.so \
    vendor/htc/glacier/proprietary/librilswitch.so:/system/lib/librilswitch.so \
    vendor/htc/glacier/proprietary/libloc_api-rpc.so:/system/lib/libloc_api-rpc.so \
    vendor/htc/glacier/proprietary/libloc_api.so:/system/lib/libloc_api.so \
    vendor/htc/glacier/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/glacier/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/glacier/proprietary/libmm-omxcore.so:/system/lib/libmm-omxcore.so \
    vendor/htc/glacier/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/glacier/proprietary/libOmxCore.so:/system/lib/libOmxCore.so \
    vendor/htc/glacier/proprietary/libOmxVdec.so:/system/lib/libOmxVdec.so \
    vendor/htc/glacier/proprietary/libOmxVenc.so:/system/lib/libOmxVenc.so \
    vendor/htc/glacier/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/glacier/proprietary/libqcomm_omx.so:/system/lib/libqcomm_omx.so \
    vendor/htc/glacier/proprietary/libvoAACDec.so:/system/lib/libvoAACDec.so \
    vendor/htc/glacier/proprietary/libvoAMRNBDec.so:/system/lib/libvoAMRNBDec.so \
    vendor/htc/glacier/proprietary/libvoAMRWBDec.so:/system/lib/libvoAMRWBDec.so \
    vendor/htc/glacier/proprietary/libvoAndroid.so:/system/lib/libvoAndroid.so \
    vendor/htc/glacier/proprietary/libvoH264Dec.so:/system/lib/libvoH264Dec.so \
    vendor/htc/glacier/proprietary/libvoicesearch.so:/system/lib/libvoicesearch.so \
    vendor/htc/glacier/proprietary/libvomemedia.so:/system/lib/libvomemedia.so \
    vendor/htc/glacier/proprietary/libvoMMCCRRS.so:/system/lib/libvoMMCCRRS.so \
    vendor/htc/glacier/proprietary/libvoMP3Dec.so:/system/lib/libvoMP3Dec.so \
    vendor/htc/glacier/proprietary/libvoMPEG4Dec.so:/system/lib/libvoMPEG4Dec.so \
    vendor/htc/glacier/proprietary/libvoOMXME.so:/system/lib/libvoOMXME.so \
    vendor/htc/glacier/proprietary/libvoOMXOne.so:/system/lib/libvoOMXOne.so \
    vendor/htc/glacier/proprietary/libvoPackUV.so:/system/lib/libvoPackUV.so \
    vendor/htc/glacier/proprietary/libvorbisidec.so:/system/lib/libvorbisidec.so \
    vendor/htc/glacier/proprietary/libvoSrcRTSP.so:/system/lib/libvoSrcRTSP.so \
    vendor/htc/glacier/proprietary/libvoVidDec.so:/system/lib/libvoVidDec.so \
    vendor/htc/glacier/proprietary/logcat2:/system/bin/logcat2 \
    vendor/htc/glacier/proprietary/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/glacier/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/glacier/proprietary/mm_property.conf:/system/etc/mm_property.conf \
    vendor/htc/glacier/proprietary/vidc_720p_command_control.fw:/system/etc/firmware/vidc_720p_command_control.fw \
    vendor/htc/glacier/proprietary/vidc_720p_h263_dec_mc.fw:/system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/htc/glacier/proprietary/vidc_720p_h264_dec_mc.fw:/system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/htc/glacier/proprietary/vidc_720p_h264_enc_mc.fw:/system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/htc/glacier/proprietary/vidc_720p_mp2_dec_mc.fw:/system/etc/firmware/vidc_720p_mp2_dec_mc.fw \
    vendor/htc/glacier/proprietary/vidc_720p_mp4_dec_mc.fw:/system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/htc/glacier/proprietary/vidc_720p_mp4_enc_mc.fw:/system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/htc/glacier/proprietary/vidc_720p_vc1_dec_mc.fw:/system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
    vendor/htc/glacier/proprietary/Glacier_SPK.acdb:/system/etc/firmware/Glacier_SPK.acdb \
    vendor/htc/glacier/proprietary/vomeComp.cfg:/system/etc/vomeComp.cfg \
    vendor/htc/glacier/proprietary/vomeplay.cfg:/system/etc/vomeplay.cfg \
    vendor/htc/glacier/proprietary/voVidDec.dat:/system/etc/voVidDec.dat \
    vendor/htc/glacier/proprietary/vpimg:/system/etc/vpimg \
    vendor/htc/glacier/proprietary/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
    vendor/htc/glacier/proprietary/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw
