# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/ville/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/htc/ville/proprietary/bin/ewtzmud:/system/bin/ewtzmud \
        vendor/htc/ville/proprietary/lib/libchromatix_s5k3h2yx_default_video.so:/system/lib/libchromatix_s5k3h2yx_default_video.so \
        vendor/htc/ville/proprietary/lib/libchromatix_s5k3h2yx_hdr.so:/system/lib/libchromatix_s5k3h2yx_hdr.so \
        vendor/htc/ville/proprietary/lib/libchromatix_s5k3h2yx_hfr.so:/system/lib/libchromatix_s5k3h2yx_hfr.so \
        vendor/htc/ville/proprietary/lib/libchromatix_s5k3h2yx_preview.so:/system/lib/libchromatix_s5k3h2yx_preview.so \
        vendor/htc/ville/proprietary/lib/libchromatix_s5k3h2yx_zsl.so:/system/lib/libchromatix_s5k3h2yx_zsl.so \
        vendor/htc/ville/proprietary/lib/hw/sensors.ville.so:/system/lib/hw/sensors.ville.so \
        vendor/htc/ville/proprietary/etc/firmware/modem.b00:/system/etc/firmware/modem.b00 \
        vendor/htc/ville/proprietary/etc/firmware/modem.b01:/system/etc/firmware/modem.b01 \
        vendor/htc/ville/proprietary/etc/firmware/modem.b02:/system/etc/firmware/modem.b02 \
        vendor/htc/ville/proprietary/etc/firmware/modem.b03:/system/etc/firmware/modem.b03 \
        vendor/htc/ville/proprietary/etc/firmware/modem.b04:/system/etc/firmware/modem.b04 \
        vendor/htc/ville/proprietary/etc/firmware/modem.b06:/system/etc/firmware/modem.b06 \
        vendor/htc/ville/proprietary/etc/firmware/modem.b07:/system/etc/firmware/modem.b07 \
        vendor/htc/ville/proprietary/etc/firmware/modem.mdt:/system/etc/firmware/modem.mdt \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b00:/system/etc/firmware/modem_fw.b00 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b01:/system/etc/firmware/modem_fw.b01 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b02:/system/etc/firmware/modem_fw.b02 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b03:/system/etc/firmware/modem_fw.b03 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b04:/system/etc/firmware/modem_fw.b04 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b05:/system/etc/firmware/modem_fw.b05 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b06:/system/etc/firmware/modem_fw.b06 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b07:/system/etc/firmware/modem_fw.b07 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b08:/system/etc/firmware/modem_fw.b08 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b09:/system/etc/firmware/modem_fw.b09 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b10:/system/etc/firmware/modem_fw.b10 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b13:/system/etc/firmware/modem_fw.b13 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b14:/system/etc/firmware/modem_fw.b14 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b21:/system/etc/firmware/modem_fw.b21 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b22:/system/etc/firmware/modem_fw.b22 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b23:/system/etc/firmware/modem_fw.b23 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b25:/system/etc/firmware/modem_fw.b25 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b26:/system/etc/firmware/modem_fw.b26 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.b29:/system/etc/firmware/modem_fw.b29 \
        vendor/htc/ville/proprietary/etc/firmware/modem_fw.mdt:/system/etc/firmware/modem_fw.mdt \
        vendor/htc/ville/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
        vendor/htc/ville/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so
