# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/fireball/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/htc/fireball/proprietary/lib/libchromatix_s5k3h2yx_default_video.so:/system/lib/libchromatix_s5k3h2yx_default_video.so \
        vendor/htc/fireball/proprietary/lib/libchromatix_s5k3h2yx_hdr.so:/system/lib/libchromatix_s5k3h2yx_hdr.so \
        vendor/htc/fireball/proprietary/lib/libchromatix_s5k3h2yx_hfr.so:/system/lib/libchromatix_s5k3h2yx_hfr.so \
        vendor/htc/fireball/proprietary/lib/libchromatix_s5k3h2yx_preview.so:/system/lib/libchromatix_s5k3h2yx_preview.so \
        vendor/htc/fireball/proprietary/lib/libchromatix_s5k3h2yx_zsl.so:/system/lib/libchromatix_s5k3h2yx_zsl.so \
        vendor/htc/fireball/proprietary/lib/libchromatix_s5k6a1gx_default_video.so:/system/lib/libchromatix_s5k6a1gx_default_video.so \
        vendor/htc/fireball/proprietary/lib/libchromatix_s5k6a1gx_preview.so:/system/lib/libchromatix_s5k6a1gx_preview.so \
        vendor/htc/fireball/proprietary/lib/libchromatix_s5k6a1gx_zsl.so:/system/lib/libchromatix_s5k6a1gx_zsl.so \
        vendor/htc/fireball/proprietary/lib/hw/nfc.default.so:/system/lib/hw/nfc.default.so \
        vendor/htc/fireball/proprietary/vendor/firmware/libpn544_fw.so:/system/vendor/firmware/libpn544_fw.so \
        vendor/htc/fireball/proprietary/lib/hw/sensors.default.so:/system/lib/hw/sensors.default.so \
        vendor/htc/fireball/proprietary/bin/netmgrd:/system/bin/netmgrd \
        vendor/htc/fireball/proprietary/bin/qmuxd:/system/bin/qmuxd \
        vendor/htc/fireball/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
        vendor/htc/fireball/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
        vendor/htc/fireball/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
        vendor/htc/fireball/proprietary/lib/libidl.so:/system/lib/libidl.so \
        vendor/htc/fireball/proprietary/lib/libqdi.so:/system/lib/libqdi.so \
        vendor/htc/fireball/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
        vendor/htc/fireball/proprietary/lib/libqmi_cci.so:/system/lib/libqmi_cci.so \
        vendor/htc/fireball/proprietary/lib/libqmi_common_so.so:/system/lib/libqmi_common_so.so \
        vendor/htc/fireball/proprietary/lib/libqmi_csi.so:/system/lib/libqmi_csi.so \
        vendor/htc/fireball/proprietary/lib/libqmi_encdec.so:/system/lib/libqmi_encdec.so \
        vendor/htc/fireball/proprietary/lib/libqmiservices.so:/system/lib/libqmiservices.so \
        vendor/htc/fireball/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
        vendor/htc/fireball/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
        vendor/htc/fireball/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
        vendor/htc/fireball/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so
